#!/bin/sh

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")

PATTERN='^(update|chore|feat): [a-z ]+$'

if ! echo "$MSG" | grep -Eq "$PATTERN"; then
  echo " Invalid commit message"
  echo " Allowed format:"
  echo "   update: env variables"
  echo "   chore: clean build"
  echo "   feat: add login"
  exit 1
fi

exit 0
